### ISSUE TITLE
Add TRF read, write

### ISSUE THREAD

**Issue by ofgulban** [ofgulban/bvbabel#16]
Also consider adding an example script for converting TRF information to BIDS task events format: [/home/faruk/Documents/test_bvbabel/vtc2/anatomy_tmean.vmr](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/05-task-events.html)

@nausikaa8 , maybe you would be interested in contributing this. Let me know.

**Comment by nausikaa8** [comment]
Thanks @ofgulban, now testing TRF read, write; pull request to follow soon.

**Comment by ofgulban** [comment]
@nausikaa8 , I see that you have pushed TRF contributions to your fork, but I did not receive a pull request. Can you try sending a pull request again?

**Comment by nausikaa8** [comment]
Thanks for the feedback @ofgulban, the pull request should have worked now, please let me know if not.

**Comment by ofgulban** [comment]
Completed with #18
