### ISSUE TITLE
Additional test data for PRT

### ISSUE THREAD

**Issue by ofgulban** [ofgulban/bvbabel#19]
I am wondering if @nausikaa8 has additional test data for PRT? I have finished implementing read write functions. It would be helpful if these functions are tested with other PRT variants.

@nausikaa8  would you have time to help with this? Nothing urgent but your help is highly appreciated.

**Comment by nausikaa8** [comment]
Good, that is fast, @ofgulban. I can upload PRT variations in fileversion (2,3), resolution (msec,vol), parametric weights (0,1). If you'd be interested, where would you like me to send them? Zipped or not ;-)

**Comment by ofgulban** [comment]
That is great. Can you pull request these text files?

**Comment by nausikaa8** [comment]
Ok @ofgulban, pull request opened!

**Comment by ofgulban** [comment]
Thanks @nausikaa8 , with the recent commits (aaf4d8027dde81fb9836431ca91c6a2b8e584e08, d1ca943a893bfb6cb08eda224f6f4d11987fe9cf, 249da438d8f69d86fca3c7c5104230c1b29d8790), it seems that all the additonal PRT files are read and written properly. Feel free to have a look.

Next is to write file I/O tests for these PRT files.
