### ISSUE TITLE
timings are imported as float arrays

### ISSUE THREAD

**Issue by ju-ec** [ofgulban/bvbabel#22]
The timings are imported as float arrays, this will result in problems when saving and re-importing any changed PRTs in BV.
Using int arrays should solve the problem.

**Comment by ofgulban** [comment]
Addressed with aaf4d8027dde81fb9836431ca91c6a2b8e584e08 and 249da438d8f69d86fca3c7c5104230c1b29d8790 .

Thanks @ju-ec . Please don't hesitate to open a new issue if you encounter other problems.
