### ISSUE TITLE
Cannot  read PRT files with tab-separated timings

### ISSUE THREAD

**Issue by ju-ec** [ofgulban/bvbabel#27]
bvbabel cannot read any PRTs that save onset and offset event times separated with tabs.
To fix this problem I would suggest to replace the following lines in  `prt.py`:

```
values = lines[i+2+j].split(" ")
```
with
```
values = lines[i+2+j].split()
```
This will make sure that any whitespace can be used as separator between the timings.Or use `values = lines[i+2+j].split(maxsplit=1)` to make sure that each line is splitted only once.

Probably less common, but also possible would be the TAB separator for the color definition. Therefore, I would also suggest to replace the following line:

```
values = lines[i+2+n].split(" ")
```
with
```
values = lines[i+2+n].split() 
```

**Comment by ofgulban** [comment]
Thanks @ju-ec  for opening this issue and giving your tip. Tabs are considered now.
