### ISSUE TITLE
MTC support and example

### ISSUE THREAD

**Issue by neurolabusc** [ofgulban/bvbabel#4]
As a feature request, it would be great if this software could support [MTC](https://support.brainvoyager.com/brainvoyager/automation-development/84-file-formats/350-users-guide-2-3-the-format-of-mtc-files) format and include an example MTC file.

**Comment by ofgulban** [comment]
Thanks @neurolabusc for the requiest, it seems that MTC is a rather straightforward format. I will prioritize this.

**Comment by ofgulban** [comment]
Sorry, it take ages to get back to this due to unforeseen events. But I will look into it soon.

**Comment by ofgulban** [comment]
I have added MTC read and write support, together with example data, see the following commits:
1. 3e5edb574fc34e525d71d3251b7328b1436c2465
2. f63e8a23d092d4bbfecf52b60ecf74cf98768e9a

Thanks for opening this issue @neurolabusc .
