### ISSUE TITLE
VTC reader returns 0 for all voxel activations

### ISSUE THREAD

**Issue by AidaMirebrahimi** [ofgulban/bvbabel#43]
when I use the command to read a VTC file that was created by brain voyager it returns 0 for all voxel values. When I look at the VTC data from the same file inside brain voyager the values are not zero. The header has the correct information though.
 VTC_header, VTC_data = bvbabel.vtc.read_vtc(VTC_path, rearrange_data_axes=False)

**Comment by ofgulban** [comment]
hello @AidaMirebrahimi , thansk for your question. I am currently in a conference and will only be able to look into this in the first week of august. It would be useful if you can share one of your vtc files for me to look into it.

**Comment by ofgulban** [comment]
@AidaMirebrahimi , would it be possible for you to send your VTC data so that I can have a detailed look? I cannot replicate this with our example data.

**Comment by ofgulban** [comment]
Closing. Can be re-opened if the issuer responds.
