### ISSUE TITLE
Add an example for read_fmr_write_nifti with correct header information

### ISSUE THREAD

**Issue by kenshukoiso** [ofgulban/bvbabel#53]
Hi Faruk,

I would like to save a nifti file from an fmr file with copying the correct header information from the fmr file, especially the voxel size information. 
I have tried it with the following approach: 

1. Loading another nifti file as a template just to get a nifti header data frame 
2. ⁠Overwrite header info with this 
```
  ⁠nii.header["pixdim"][1] = header['InplaneResolutionX']
  nii.header["pixdim"][2] = header['InplaneResolutionY']
  nii.header["pixdim"][3] = header['SliceThickness']
  nii.header["pixdim"][4] = header['NrOfVolumes']
```
3. ⁠Then just save it with the updated header
```
img = nb.Nifti1Image(data, affine=np.eye(4), header=nii.header)
nb.save(img, outname)
```

But somehow the created nifti file is still with the header telling 1x1x1 mm voxel size, even though the BV header says 0.8 mm iso.

Since I cannot upload BV files here, I have uploaded on here: https://drive.google.com/drive/folders/1n1ncxFYnnOEPnC881ex3DLtpo1YcKIOe?usp=sharing

Thank you so much for your help in advance!

Best regards,
Kenshu

**Comment by ofgulban** [comment]
Hi Kenshu,

Thanks for opening this issue and writing clearly about the problem you are facing. I have used the following changes in the `read_fmr_export_nifti.py` (see under 'carry over header information section'):
```
"""Read BrainVoyager FMR file format and exxport it as Nifti."""

import os
import numpy as np
import nibabel as nb
import bvbabel

FILE = "/Users/faruk/data/temp-kenshu/S05_ses1_run01_SCSA_3DMCTS_THPGLMF6c_ref.fmr"

# =============================================================================
# Load fmr
header, data = bvbabel.fmr.read_fmr(FILE)

# Save nifti for testing
basename = FILE.split(os.extsep, 1)[0]
outname = "{}_bvbabel.nii.gz".format(basename)

# Export nifti (assign an identity matrix as affine with default header)
img = nb.Nifti1Image(data, affine=np.eye(4))

# Carry over equivalent header information
img.header["pixdim"][1] = header['InplaneResolutionX']
img.header["pixdim"][2] = header['InplaneResolutionY']
img.header["pixdim"][3] = header['SliceThickness']
img.header["pixdim"][4] = float(header['TR']) / 1000  # ms to s
img.affine[0, 0] *= img.header["pixdim"][1]
img.affine[1, 1] *= img.header["pixdim"][2]
img.affine[2, 2] *= img.header["pixdim"][3]

# Save
nb.save(img, outname)

print("Finished.")
```

Upon exporting the nifti with this script, nifti header looks good. Checked with **niimath** and **itksnap**:

<img width="908" alt="Screenshot 2024-04-13 at 12 23 59" src="https://github.com/ofgulban/bvbabel/assets/4668327/36e22fb0-af43-4900-a8ce-f47e55415b66">

<img width="628" alt="Screenshot 2024-04-13 at 12 26 46" src="https://github.com/ofgulban/bvbabel/assets/4668327/a204373e-c825-4523-b4bd-4e1d3d8bbd10">

Let me know if trying the script above works for you or not.

**Comment by ofgulban** [comment]
Also, another note:
```
  nii.header["pixdim"][4] = header['NrOfVolumes']
```
line of your code is incorrect in the way that pixdim 4 is the size of "time" that is TR in seconds. You were putting number of measurements there.

**Comment by kenshukoiso** [comment]
Thank you so much for taking care of my issue immediately!
It works well for my circumstances as well!
Also, thanks for telling me my error, I learnt it.
Thank you so much :)
